name: 🐞 Bug Report
description: Report a reproducible bug in the project
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the details below."
  - type: input
    id: title
    attributes:
      label: Title
      description: Short, descriptive title of the bug.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, version, etc.
