name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the requested feature.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Explain why this feature is useful, who it benefits, etc.
    validations:
      required: true
